package com.ihsinformatics.micronutrient.model.pojos;
// Generated Jun 15, 2015 10:01:48 AM by Hibernate Tools 4.3.1



/**
 * DistrictLogisticSummary generated by hbm2java
 */
public class DistrictLogisticSummary  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int summaryId;
     private String reportingMonth;
     private String openingStockKio3;
     private String receivedFromGeneraCurrentMonth;
     private String kio3Sold;
     private String closingStockKio3;
     private String remarks;

    public DistrictLogisticSummary() {
    }

    public DistrictLogisticSummary(int summaryId, String reportingMonth, String openingStockKio3, String receivedFromGeneraCurrentMonth, String kio3Sold, String closingStockKio3, String remarks) {
       this.summaryId = summaryId;
       this.reportingMonth = reportingMonth;
       this.openingStockKio3 = openingStockKio3;
       this.receivedFromGeneraCurrentMonth = receivedFromGeneraCurrentMonth;
       this.kio3Sold = kio3Sold;
       this.closingStockKio3 = closingStockKio3;
       this.remarks = remarks;
    }
   
    public int getSummaryId() {
        return this.summaryId;
    }
    
    public void setSummaryId(int summaryId) {
        this.summaryId = summaryId;
    }
    public String getReportingMonth() {
        return this.reportingMonth;
    }
    
    public void setReportingMonth(String reportingMonth) {
        this.reportingMonth = reportingMonth;
    }
    public String getOpeningStockKio3() {
        return this.openingStockKio3;
    }
    
    public void setOpeningStockKio3(String openingStockKio3) {
        this.openingStockKio3 = openingStockKio3;
    }
    public String getReceivedFromGeneraCurrentMonth() {
        return this.receivedFromGeneraCurrentMonth;
    }
    
    public void setReceivedFromGeneraCurrentMonth(String receivedFromGeneraCurrentMonth) {
        this.receivedFromGeneraCurrentMonth = receivedFromGeneraCurrentMonth;
    }
    public String getKio3Sold() {
        return this.kio3Sold;
    }
    
    public void setKio3Sold(String kio3Sold) {
        this.kio3Sold = kio3Sold;
    }
    public String getClosingStockKio3() {
        return this.closingStockKio3;
    }
    
    public void setClosingStockKio3(String closingStockKio3) {
        this.closingStockKio3 = closingStockKio3;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


