package com.ihsinformatics.micronutrient.model.pojos;

// Generated Jun 15, 2015 10:01:48 AM by Hibernate Tools 4.3.1



/**
 * District generated by hbm2java
 */
public class District implements java.io.Serializable
{


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int districtId;
	private String districtName;
	private byte province;

	public District()
	{
	}

	public District(int districtId, String districtName, byte province)
	{
		this.districtId = districtId;
		this.districtName = districtName;
		this.province = province;
	}

	public int getDistrictId()
	{
		return this.districtId;
	}

	public void setDistrictId(int districtId)
	{
		this.districtId = districtId;
	}

	public String getDistrictName()
	{
		return this.districtName;
	}

	public void setDistrictName(String districtName)
	{
		this.districtName = districtName;
	}

	public byte getProvince()
	{
		return this.province;
	}

	public void setProvince(byte province)
	{
		this.province = province;
	}

}
