package com.ihsinformatics.micronutrient.model.pojos;
// Generated Jun 15, 2015 10:01:48 AM by Hibernate Tools 4.3.1



/**
 * Province generated by hbm2java
 */
public class Province  implements java.io.Serializable {


     private byte provinceId;
     private String provinceName;

    public Province() {
    }

    public Province(byte provinceId, String provinceName) {
       this.provinceId = provinceId;
       this.provinceName = provinceName;
    }
   
    public byte getProvinceId() {
        return this.provinceId;
    }
    
    public void setProvinceId(byte provinceId) {
        this.provinceId = provinceId;
    }
    public String getProvinceName() {
        return this.provinceName;
    }
    
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }




}


