package com.ihsinformatics.micronutrient.model.pojos;
// Generated Jun 15, 2015 10:01:48 AM by Hibernate Tools 4.3.1



/**
 * QclCollection generated by hbm2java
 */
public class QclCollection  implements java.io.Serializable {


     private int qclCollectionId;
     private int labId;
     private String sampleDistrict;
     private String sampleSource;

    public QclCollection() {
    }

    public QclCollection(int qclCollectionId, int labId, String sampleDistrict, String sampleSource) {
       this.qclCollectionId = qclCollectionId;
       this.labId = labId;
       this.sampleDistrict = sampleDistrict;
       this.sampleSource = sampleSource;
    }
   
    public int getQclCollectionId() {
        return this.qclCollectionId;
    }
    
    public void setQclCollectionId(int qclCollectionId) {
        this.qclCollectionId = qclCollectionId;
    }
    public int getLabId() {
        return this.labId;
    }
    
    public void setLabId(int labId) {
        this.labId = labId;
    }
    public String getSampleDistrict() {
        return this.sampleDistrict;
    }
    
    public void setSampleDistrict(String sampleDistrict) {
        this.sampleDistrict = sampleDistrict;
    }
    public String getSampleSource() {
        return this.sampleSource;
    }
    
    public void setSampleSource(String sampleSource) {
        this.sampleSource = sampleSource;
    }




}


