package com.ihsinformatics.micronutrient.model.pojos;
// Generated Jun 15, 2015 10:01:48 AM by Hibernate Tools 4.3.1



/**
 * QclLab generated by hbm2java
 */
public class QclLab  implements java.io.Serializable {


     private int labId;
     private String labName;
     private String province;
     private String district;

    public QclLab() {
    }

    public QclLab(int labId, String labName, String province, String district) {
       this.labId = labId;
       this.labName = labName;
       this.province = province;
       this.district = district;
    }
   
    public int getLabId() {
        return this.labId;
    }
    
    public void setLabId(int labId) {
        this.labId = labId;
    }
    public String getLabName() {
        return this.labName;
    }
    
    public void setLabName(String labName) {
        this.labName = labName;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }




}


