package com.ihsinformatics.micronutrient.model.pojos;
// Generated Jun 15, 2015 10:01:48 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * QclSample generated by hbm2java
 */
public class QclSample  implements java.io.Serializable {


     private int sampleId;
     private int labId;
     private int collectionId;
     private String information;
     private String category;
     private Date collectionDate;
     private Date analysisDate;
     private String results;

    public QclSample() {
    }

    public QclSample(int sampleId, int labId, int collectionId, String information, String category, Date collectionDate, Date analysisDate, String results) {
       this.sampleId = sampleId;
       this.labId = labId;
       this.collectionId = collectionId;
       this.information = information;
       this.category = category;
       this.collectionDate = collectionDate;
       this.analysisDate = analysisDate;
       this.results = results;
    }
   
    public int getSampleId() {
        return this.sampleId;
    }
    
    public void setSampleId(int sampleId) {
        this.sampleId = sampleId;
    }
    public int getLabId() {
        return this.labId;
    }
    
    public void setLabId(int labId) {
        this.labId = labId;
    }
    public int getCollectionId() {
        return this.collectionId;
    }
    
    public void setCollectionId(int collectionId) {
        this.collectionId = collectionId;
    }
    public String getInformation() {
        return this.information;
    }
    
    public void setInformation(String information) {
        this.information = information;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public Date getCollectionDate() {
        return this.collectionDate;
    }
    
    public void setCollectionDate(Date collectionDate) {
        this.collectionDate = collectionDate;
    }
    public Date getAnalysisDate() {
        return this.analysisDate;
    }
    
    public void setAnalysisDate(Date analysisDate) {
        this.analysisDate = analysisDate;
    }
    public String getResults() {
        return this.results;
    }
    
    public void setResults(String results) {
        this.results = results;
    }




}


