package com.ihsinformatics.micronutrient.model.pojos;
// Generated Jun 15, 2015 11:25:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sp generated by hbm2java
 */
public class Sp  implements java.io.Serializable {


     private int id;
     private int spId;
     private String spName;
     private String contactPerson;
     private String address;
     private String contact1;
     private String contact2;
     private String contact3;
     private int tehsilId;
     private float latitude;
     private float longitude;
     private Set spVisits = new HashSet(0);

    public Sp() {
    }

	
    public Sp(int id, int spId, String spName, String contactPerson, String address, String contact1, String contact2, String contact3, int tehsilId, float latitude, float longitude) {
        this.id = id;
        this.spId = spId;
        this.spName = spName;
        this.contactPerson = contactPerson;
        this.address = address;
        this.contact1 = contact1;
        this.contact2 = contact2;
        this.contact3 = contact3;
        this.tehsilId = tehsilId;
        this.latitude = latitude;
        this.longitude = longitude;
    }
    public Sp(int id, int spId, String spName, String contactPerson, String address, String contact1, String contact2, String contact3, int tehsilId, float latitude, float longitude, Set spVisits) {
       this.id = id;
       this.spId = spId;
       this.spName = spName;
       this.contactPerson = contactPerson;
       this.address = address;
       this.contact1 = contact1;
       this.contact2 = contact2;
       this.contact3 = contact3;
       this.tehsilId = tehsilId;
       this.latitude = latitude;
       this.longitude = longitude;
       this.spVisits = spVisits;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getSpId() {
        return this.spId;
    }
    
    public void setSpId(int spId) {
        this.spId = spId;
    }
    public String getSpName() {
        return this.spName;
    }
    
    public void setSpName(String spName) {
        this.spName = spName;
    }
    public String getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getContact1() {
        return this.contact1;
    }
    
    public void setContact1(String contact1) {
        this.contact1 = contact1;
    }
    public String getContact2() {
        return this.contact2;
    }
    
    public void setContact2(String contact2) {
        this.contact2 = contact2;
    }
    public String getContact3() {
        return this.contact3;
    }
    
    public void setContact3(String contact3) {
        this.contact3 = contact3;
    }
    public int getTehsilId() {
        return this.tehsilId;
    }
    
    public void setTehsilId(int tehsilId) {
        this.tehsilId = tehsilId;
    }
    public float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(float latitude) {
        this.latitude = latitude;
    }
    public float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(float longitude) {
        this.longitude = longitude;
    }
    public Set getSpVisits() {
        return this.spVisits;
    }
    
    public void setSpVisits(Set spVisits) {
        this.spVisits = spVisits;
    }




}


