package com.ihsinformatics.micronutrient.model.pojos;

// Generated Jun 15, 2015 11:25:10 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SpVisit generated by hbm2java
 */
public class SpVisit implements java.io.Serializable
{


	private int visitId;
	private Sp sp;
	private Date visitDate;
	private Date visitTime;
	private String awareOfIodizationProcess;
	private String dropMatchesChakki;
	private String kio3PreparedAsStandard;
	private String totalSaltProduced;
	private String edibleSaltProduction;
	private String iodizedSaltProduced;
	private String uniodizedSaltProduced;
	private String previousKio3Stock;
	private String kio3Received;
	private String existingStock;
	private String kio3Utilized;
	private String rtkResultsNoIodine;
	private String rtkResults115;
	private String rtkResults1629;
	private String rtkResults30Above;
	private String dripFeed;
	private String dripSet;
	private String rtks;
	private String noOfSamplesCollectedForQcl;
	private String packaging;
	private String remarks;

	public SpVisit()
	{
	}

	/**
	 * @param visitId
	 * @param sp
	 * @param visitDate
	 * @param visitTime
	 * @param awareOfIodizationProcess
	 * @param dropMatchesChakki
	 * @param kio3PreparedAsStandard
	 * @param totalSaltProduced
	 * @param edibleSaltProduction
	 * @param iodizedSaltProduced
	 * @param uniodizedSaltProduced
	 * @param previousKio3Stock
	 * @param kio3Received
	 * @param existingStock
	 * @param kio3Utilized
	 * @param rtkResultsNoIodine
	 * @param rtkResults115
	 * @param rtkResults1629
	 * @param rtkResults30Above
	 * @param dripFeed
	 * @param dripSet
	 * @param rtks
	 * @param noOfSamplesCollectedForQcl
	 * @param packaging
	 * @param remarks
	 */
	public SpVisit(int visitId, Sp sp, Date visitDate, Date visitTime, String awareOfIodizationProcess, String dropMatchesChakki, String kio3PreparedAsStandard, String totalSaltProduced,
			String edibleSaltProduction, String iodizedSaltProduced, String uniodizedSaltProduced, String previousKio3Stock, String kio3Received, String existingStock, String kio3Utilized,
			String rtkResultsNoIodine, String rtkResults115, String rtkResults1629, String rtkResults30Above, String dripFeed, String dripSet, String rtks,
			String noOfSamplesCollectedForQcl, String packaging, String remarks)
	{
		this.visitId = visitId;
		this.sp = sp;
		this.visitDate = visitDate;
		this.visitTime = visitTime;
		this.awareOfIodizationProcess = awareOfIodizationProcess;
		this.dropMatchesChakki = dropMatchesChakki;
		this.kio3PreparedAsStandard = kio3PreparedAsStandard;
		this.totalSaltProduced = totalSaltProduced;
		this.edibleSaltProduction = edibleSaltProduction;
		this.iodizedSaltProduced = iodizedSaltProduced;
		this.uniodizedSaltProduced = uniodizedSaltProduced;
		this.previousKio3Stock = previousKio3Stock;
		this.kio3Received = kio3Received;
		this.existingStock = existingStock;
		this.kio3Utilized = kio3Utilized;
		this.rtkResultsNoIodine = rtkResultsNoIodine;
		this.rtkResults115 = rtkResults115;
		this.rtkResults1629 = rtkResults1629;
		this.rtkResults30Above = rtkResults30Above;
		this.dripFeed = dripFeed;
		this.dripSet = dripSet;
		this.rtks = rtks;
		this.noOfSamplesCollectedForQcl = noOfSamplesCollectedForQcl;
		this.packaging = packaging;
		this.remarks = remarks;
	}

	public int getVisitId()
	{
		return this.visitId;
	}

	public void setVisitId(int visitId)
	{
		this.visitId = visitId;
	}

	public Sp getSp()
	{
		return this.sp;
	}

	public void setSp(Sp sp)
	{
		this.sp = sp;
	}

	public Date getVisitDate()
	{
		return this.visitDate;
	}

	public void setVisitDate(Date visitDate)
	{
		this.visitDate = visitDate;
	}

	public Date getVisitTime()
	{
		return this.visitTime;
	}

	public void setVisitTime(Date visitTime)
	{
		this.visitTime = visitTime;
	}

	public String getAwareOfIodizationProcess()
	{
		return this.awareOfIodizationProcess;
	}

	public void setAwareOfIodizationProcess(String awareOfIodizationProcess)
	{
		this.awareOfIodizationProcess = awareOfIodizationProcess;
	}

	public String getDropMatchesChakki()
	{
		return this.dropMatchesChakki;
	}

	public void setDropMatchesChakki(String dropMatchesChakki)
	{
		this.dropMatchesChakki = dropMatchesChakki;
	}

	public String getKio3PreparedAsStandard()
	{
		return this.kio3PreparedAsStandard;
	}

	public void setKio3PreparedAsStandard(String kio3PreparedAsStandard)
	{
		this.kio3PreparedAsStandard = kio3PreparedAsStandard;
	}

	public String getTotalSaltProduced()
	{
		return this.totalSaltProduced;
	}

	public void setTotalSaltProduced(String totalSaltProduced)
	{
		this.totalSaltProduced = totalSaltProduced;
	}

	public String getEdibleSaltProduction()
	{
		return this.edibleSaltProduction;
	}

	public void setEdibleSaltProduction(String edibleSaltProduction)
	{
		this.edibleSaltProduction = edibleSaltProduction;
	}

	public String getIodizedSaltProduced()
	{
		return this.iodizedSaltProduced;
	}

	public void setIodizedSaltProduced(String iodizedSaltProduced)
	{
		this.iodizedSaltProduced = iodizedSaltProduced;
	}

	public String getUniodizedSaltProduced()
	{
		return this.uniodizedSaltProduced;
	}

	public void setUniodizedSaltProduced(String uniodizedSaltProduced)
	{
		this.uniodizedSaltProduced = uniodizedSaltProduced;
	}

	public String getPreviousKio3Stock()
	{
		return this.previousKio3Stock;
	}

	public void setPreviousKio3Stock(String previousKio3Stock)
	{
		this.previousKio3Stock = previousKio3Stock;
	}

	public String getKio3Received()
	{
		return this.kio3Received;
	}

	public void setKio3Received(String kio3Received)
	{
		this.kio3Received = kio3Received;
	}

	public String getExistingStock()
	{
		return this.existingStock;
	}

	public void setExistingStock(String existingStock)
	{
		this.existingStock = existingStock;
	}

	public String getKio3Utilized()
	{
		return this.kio3Utilized;
	}

	public void setKio3Utilized(String kio3Utilized)
	{
		this.kio3Utilized = kio3Utilized;
	}

	public String getRtkResultsNoIodine()
	{
		return this.rtkResultsNoIodine;
	}

	public void setRtkResultsNoIodine(String rtkResultsNoIodine)
	{
		this.rtkResultsNoIodine = rtkResultsNoIodine;
	}

	public String getRtkResults115()
	{
		return this.rtkResults115;
	}

	public void setRtkResults115(String rtkResults115)
	{
		this.rtkResults115 = rtkResults115;
	}

	public String getRtkResults1629()
	{
		return this.rtkResults1629;
	}

	public void setRtkResults1629(String rtkResults1629)
	{
		this.rtkResults1629 = rtkResults1629;
	}

	public String getRtkResults30Above()
	{
		return this.rtkResults30Above;
	}

	public void setRtkResults30Above(String rtkResults30Above)
	{
		this.rtkResults30Above = rtkResults30Above;
	}

	public String getDripFeed()
	{
		return this.dripFeed;
	}

	public void setDripFeed(String dripFeed)
	{
		this.dripFeed = dripFeed;
	}

	public String getDripSet()
	{
		return this.dripSet;
	}

	public void setDripSet(String dripSet)
	{
		this.dripSet = dripSet;
	}

	public String getRtks()
	{
		return this.rtks;
	}

	public void setRtks(String rtks)
	{
		this.rtks = rtks;
	}

	public String getNoOfSamplesCollectedForQcl()
	{
		return this.noOfSamplesCollectedForQcl;
	}

	public void setNoOfSamplesCollectedForQcl(String noOfSamplesCollectedForQcl)
	{
		this.noOfSamplesCollectedForQcl = noOfSamplesCollectedForQcl;
	}

	public String getPackaging()
	{
		return this.packaging;
	}

	public void setPackaging(String packaging)
	{
		this.packaging = packaging;
	}

	public String getRemarks()
	{
		return this.remarks;
	}

	public void setRemarks(String remarks)
	{
		this.remarks = remarks;
	}




}
